name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compile-nifs:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: linux-x86_64
          - os: macos-latest
            target: macos-aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2.7.3
      - run: cargo xtask
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: compiled-nifs-${{ matrix.target }}
          path: priv/lib/*.so
  test:
    runs-on: ubuntu-latest
    needs: compile-nifs
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: erlef/setup-beam@v1.15.4
        with:
          otp-version: "26.0.2"
          gleam-version: "1.1.0"
          rebar3-version: "3"
      - run: gleam format --check src test
      - run: gleam deps download
      - uses: actions/download-artifact@v4.1.7
        with:
          name: compiled-nifs-linux-x86_64
          path: priv/lib
      - run: gleam test --target erlang
